---
# tasks file for lighthouse
- name: Get lighthouse
  hosts: lighthouse
  pre_tasks:
    - name: Install GIT
      become: true
      ansible.builtin.package:
        name: git
        state: present
  tasks:
    - name: Get lighthouse distrib
      ansible.builtin.git:
        repo: "{{ url_to_lighthouse }}"
        version: "master"
        dest: "{{ site_path }}"
        accept_hostkey: true

- name: Prepare NGINX
  hosts: lighthouse
  handlers:
    - name: Start nginx
      become: true
      ansible.builtin.command: nginx
    - name: Restart nginx
      become: true
      ansible.builtin.command: nginx -s reload
  tasks:
    - name: Get NGINX version
      become: true
      ansible.builtin.command: nginx -v
      register: nginx_result
      ignore_errors: true
      changed_when: false
    - name: Get, unpack and configure nginx
      block:
        - name: Install the 'Development tools' package group
          become: true
          ansible.builtin.yum:
            name: "@Development tools"
            state: present
        - name: Get NGINX distrib
          ansible.builtin.get_url:
            url: "https://nginx.org/download/nginx-{{ nginx_version }}.tar.gz"
            dest: /tmp
            mode: "0644"
        - name: Unpack nginx distrib
          ansible.builtin.unarchive:
            src: /tmp/nginx-{{ nginx_version }}.tar.gz
            dest: /tmp
            remote_src: true
        - name: Configure NGINX
          ansible.builtin.command:
            cmd: ./configure --without-http_rewrite_module --without-http_gzip_module
            chdir: /tmp/nginx-{{ nginx_version }}
          register: my_output
          changed_when: my_output.rc != 0
        - name: Make NGINX
          ansible.builtin.command:
            cmd: make
            chdir: /tmp/nginx-{{ nginx_version }}
          register: my_output
          changed_when: my_output.rc != 0
        - name: Install NGINX
          become: true
          ansible.builtin.command:
            cmd: make install
            chdir: /tmp/nginx-{{ nginx_version }}
          register: my_output
          changed_when: my_output.rc != 0
        - name: Make NGINX callable
          become: true
          ansible.builtin.file:
            src: /usr/local/nginx/sbin/nginx
            dest: /usr/bin/nginx
            state: link
            mode: "0744"
          notify: Start nginx
      when:
        - nginx_result.failed
        - nginx_version not in nginx_result.stdout
    - name: Configure nginx config for site
      become: true
      ansible.builtin.template:
        src: nginx.cfg.j2
        dest: /usr/local/nginx/conf/nginx.conf
        mode: "0644"
      notify: Restart nginx
    - name: Assure that directory conf.d exist
      become: true
      ansible.builtin.file:
        path: /usr/local/nginx/conf/conf.d
        state: directory
        mode: "0644"
    - name: Make config for lighthouse
      become: true
      ansible.builtin.template:
        src: default.cfg.j2
        dest: /usr/local/nginx/conf/conf.d/default.conf
        mode: "0644"
      notify: Restart nginx
